# Generated by Django 5.2.6 on 2025-10-01 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Categoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=50)),
                ("creada_en", models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Producto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=50)),
                ("precio", models.PositiveIntegerField()),
                ("stock", models.PositiveIntegerField()),
                ("activo", models.BooleanField(default=True)),
                ("creado_en", models.DateField(auto_now_add=True)),
                ("actualizado_en", models.DateField(auto_now=True)),
                (
                    "categoria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventario.categoria",
                    ),
                ),
            ],
            options={
                "ordering": ["nombre"],
                "unique_together": {("categoria", "nombre")},
            },
        ),
    ]
